version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        image: laravel-app:latest
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db
        ports:
            - "8000:80"

    db:
        image: mysql:5.7
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root123
            MYSQL_DATABASE: tes_sera
            MYSQL_PASSWORD: root123
        networks:
            - app-network
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
